### ISSUE TITLE
Not working for pubmed

### ISSUE THREAD

**Issue by several27** [PubPeerFoundation/PubPeerBrowserExtensions#3]
Hey, your extension doesn't seem to work for PubMed, even though there are some comments on your website and PubMed mentions DOI. 

E.g.
1. https://www.ncbi.nlm.nih.gov/pubmed/25633418 -
 https://pubpeer.com/publications/FB7103F85378967E5BC08AFD94C427
2. https://www.ncbi.nlm.nih.gov/pubmed/18391985 - https://pubpeer.com/publications/90F06BAB260A131D05F2A20D4023E0
...

**Comment by XavRsl** [comment]
Hello @several27,
You're right, the extension as it is will not show the comments on the two publications you mention only because the api transition to the new site is not completely finished, meaning only old publications (commented before June 15th) will be listed by the plugin. We are planning to update the API probably next week. It will come with a new version of the extension.

Thanks.
